### PR TITLE
Cr create category

### LINKED ISSUE #9: Create a Category
As an author I would like to be able to create a new category so that I can better classify my posts.

**Given** an author is on the Category list page  
**When** they select the `Create Category` button  
**Then** they should be directed to a form in which they can enter a new category name  

**Given** an author has entered a Category name  
**When** they click the `Save` button  
**Then** a new category should be saved to the database  
**And** the author should be directed to the Category list page

### PR DESCRIPTION
**Pull request by CheoR**
# Description

On the categories tab, user can click `Create Category` and is taken to the create form.
User is redirected to the categories endpoint after creating a new category.

Closes #9 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

In `client` terminal

`git fetch --all`
`git checkout cr-create-category`
`npm start`

1. In the categories tab, click `Create Category`.
2. Add a new category.
3. User is redirected to the `categories` endpoint where the new category should appear in the list of categories.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings or errors
- [X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by hrlnsnchz — APPROVED** [review]
Categories are added on the fly. Very nice

**Review by daprieu — APPROVED** [review]
was able to create categories and see them display on the dom

**Review by notdanross — APPROVED** [review]
Works perfectly!

**Review by daprieu — APPROVED** [review]

**Review by notdanross — APPROVED** [review]

**Review by daprieu — APPROVED** [review]
creating cats works also sorry for accidentally closing this branch

**Review by hrlnsnchz — APPROVED** [review]
Funciona perfectamente. Bien echo!

**Pull request merged**
