### PR TITLE
Ap view all cats

### PR DESCRIPTION
**Pull request by daprieu**
# Description

user on client side can select category MGMT from dom and will be routed to categories path were all cats will be displayed in alphabetical order

Fixes # (11)

## Type of change
Feat.

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

- [x] This change requires a documentation update

# Testing Instructions

`git fetch --all`
`git checkout ap-viewAllCats`

go to client side webpage and select category mgmt

make sure you have categories in your database!!!

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by CheoR — APPROVED** [review]
I can see all categories.

That's a nice cat.

**Comment by daprieu** [comment]
> I can see all categories.
> 
> That's a nice cat.

haha figured it would be a fun addition !

**Review by hrlnsnchz — APPROVED** [review]
it is indeed a nice gato

**Review by notdanross — APPROVED** [review]
All (=ↀωↀ=)✧'s render!

**Pull request merged**
